version: '3.4'
services:
  docker-deploy-webhook:
    image: chalice/webhooks:latest
    environment:
      CONFIG: services
      USERNAME: chalice
      PASSWORD: lajiwo3812  
      TOKEN: 123456ABCDEF
    ports:
      - 9999:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: deploy_config_json_v2
        target: /usr/src/app/config.json
        mode: 0500
    networks:
      - auto_deploy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  auto_deploy:

configs:
  deploy_config_json_v2:
    file: ../configs/docker-deploy-webhook/config.json