version: '3.4'
services:
  mathtest:
    image: chalice/mathtest:latest
    env_file:
      - ../env/.env
      - ../env/.rabbitmq
    networks:
      - mathtest_data
      - reverse_proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 3s
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  mathtest-celery:
    image: chalice/mathtest:latest
    entrypoint: /mathtest/celery-entrypoint.sh
    env_file:
      - ../env/.env
      - ../env/.rabbitmq
    networks:
      - mathtest_data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 3s
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager


networks:
  mathtest_data:
  reverse_proxy: